# @format

version: "3.8"

services:
    app:
        container_name: dopagent_scraper_container
        build:
            context: .
            target: dev
        environment:
            APP_HOST: 0.0.0.0
            APP_PORT: 9080
        ports:
            - 9080:9080
        working_dir: /dopagent_scraper
        volumes:
            - ./:/dopagent_scraper
