from enum import Enum

DOPAGENT_BASE_URL = 'https://dopagent.indiapost.gov.in'
ACCOUNTS_PER_PAGE = 10

class LoginPage:
    AGENT_ID_INPUT = 'AuthenticationFG.USER_PRINCIPAL'
    PASSWORD_INPUT = 'AuthenticationFG.ACCESS_CODE'
    LOG_IN_BUTTON = 'Action.VALIDATE_RM_PLUS_CREDENTIALS_CATCHA_DISABLED'
    CLEAR_VALUES_BUTTON = 'Action.CLEAR_VALUES'

class MenuPage:
    DASHBOARD_BUTTON = 'HREF_Dashboard'
    CHANGE_PASSWORD_BUTTON = 'HREF_Change Password'
    ACCOUNTS_BUTTON = 'HREF_Accounts'

    AGENT_ENQIRE_AND_UPDATE_SCREEN_LINK = 'HREF_Agent Enquire & Update Screen'
    REPORTS_LINK = 'HREF_Reports'

class AccountsListPage:
    ACCOUNT_NUMBER_SEARCH_BOX = 'CustomAgentRDAccountFG.ACCOUNT_NUMBER_FOR_SEARCH'
    FETCH_ACCOUNT_BUTTON = 'Action.FETCH_INPUT_ACCOUNT'
    CLEAR_VALUES_BUTTON = 'Action.CLEAR_ACCOUNTS'

    GOTO_PREV_PAGE_BUTTON = 'Action.AgentRDActSummaryAllListing.GOTO_PREV__'
    GOTO_NEXT_PAGE_BUTTON = 'Action.AgentRDActSummaryAllListing.GOTO_NEXT__'
    GOTO_PAGE_BUTTON = 'Action.AgentRDActSummaryAllListing.GOTO_PAGE__'
    GOTO_PAGE_NUMBER_INPUT = 'CustomAgentRDAccountFG.AgentRDActSummaryAllListing_REQUESTED_PAGE_NUMBER'

    SAVE_ACCOUNTS_BUTTON = 'Action.SAVE_ACCOUNTS'
    VIEW_SAVED_INSTALLMENTS_BUTTON = 'Action.VIEW_SAVED_INSTALLMENTS'

class AccountDetailPage:
    ACCOUNT_NUMBER_ID = 'HREF_CustomAgentRDAccountFG.ACCOUNT_NUMBER'
    NAME_ID = 'HREF_CustomAgentRDAccountFG.ACCOUNT_NICKNAME'
    OPENING_DATE_ID = 'HREF_CustomAgentRDAccountFG.RD_ACCOUNT_OPEN_DATE'
    DENOMINATION_ID = 'HREF_CustomAgentRDAccountFG.RD_DESPOSIT_AMOUNT'
    TOTAL_DESPOSIT_AMOUNT_ID = 'HREF_CustomAgentRDAccountFG.RD_TOTAL_DESPOSIT_AMOUNT'
    MONTH_PAID_UPTO_ID = 'HREF_CustomAgentRDAccountFG.MONTH_PAID_UPTO_BASIC'
    NEXT_INSTALLMENT_DATE_ID = 'HREF_CustomAgentRDAccountFG.NEXT_RD_INSTALLMENT_DATE'
    LAST_DEPOSIT_DATE_ID = 'HREF_CustomAgentRDAccountFG.DATE_OF_LAST_DEPOSIT'
    REBATE_ID = 'HREF_CustomAgentRDAccountFG.REBATE'
    DEFAULT_FEE_ID = 'HREF_CustomAgentRDAccountFG.DEFAULT_FEE'
    DEFAULT_INSTALLMENT_ID = 'HREF_CustomAgentRDAccountFG.DEFAULT_INSTALLMENT'
    PENDING_INSTALLMENT_ID = 'HREF_CustomAgentRDAccountFG.PENDING_INSTALLMENT'

    BACK_BUTTON = 'Action.BACK_TO_ACCOUNT_LIST'
